### ISSUE TITLE
New website to-do's

### ISSUE THREAD

**Issue by herculeeza** [BrightID/BrightID-Docs#5]
We are moving to a new website. Last stuff left to do:

Most Important
- [x] fix mohsen's photo :p 
- [x] fix adam's photo
- [x] Upload PDF of docs: sponsorships, whitepaper
- [x] create pages for sponsorships, whitepaper
- [x] fix the privacy-policy page (headers and line breaks to [match the original page](https://www.brightid.org/wordpress/staging/privacy-policy/))
- [x]  Make sure links aren't broken for these ^
- [x]  Add a link to sponsorship dashboard somewhere
- [x]  Make sure all links work!!!
- [x]  Set up webflow account
- [x]  Fix links in navbar (global)
- [x] navigation doesn't work on the faq page
- [x] delete any sections that were added for testing, like the second get-started section
- [x] check for images that need to be resized

Medium Importance
- [x]  Fix copyright & link
- [x]  Add social links bottom right (github & twitter)
- [x]  Add some medium posts after partners section
- [x]  Add links to partner pages
- [x]  Link burnsignal under ENJOY
- [x]  grayscale all pics
- [x]  check app download links
- [x]  fix header text on mobile
- [x]  fix weird default to the message section on mobile
- [x]  Add to CONNECT: telegram & discord, also link to community hour, maybe a hashtag
- [x]  FAQ -- update, remove login question
- [x]  Buttons should change when rolled over
- [x]  Add "Get Started" to hamburger menu
- [x]  fix footer on FAQ / fix global footer
- [x]  Add Tegan to the team
- [x]  Fix order of "Get Started" Bubbles on Tablet and smaller: download first.
- [x]  menu bar color change to orange when rolled over
- [x] logo and menu bar look better white not grey, especially the logo
- [x] send form to www@brightid.org
- [ ] set account email address to www@brightid.org (requires contacting support)
- [ ] resize team photos to no more than 200 x 200 px (not 500 x 500)
- [ ] resize burn signal logo to no more than 120 x 120 px (not 500 x 500)
- [ ] resize the google play icon to no more than 296 x 104 px ( not 500 x 194)
- [ ] resize partner logos to no more than 200 x 200 px (not 500 x 500) or use svg versions
- [ ] test HiDPI on images we are storing as 4x what we're displaying (e.g. 200x200 img displayed as auto should show as 100x100 img--may require a fancy screen to test)

Nice to have
- [x]  Make GET STARTED section less ugly
- [x]  Text from NON-INVASIVE spills over sometimes, change breakpoint
- [ ]  Make header text look nicer on large screen, 2 lines maybe
- [ ]  Set up community hour wiki, or something people can use to coordinate virtual & physical meetups
- [ ]  Welcome Manual to replace FAQ
- [ ]  Fix medium syndication

**Comment by adamstallard** [comment]
need to set up webflow account before I can upload pdf docs

**Comment by adamstallard** [comment]
![image](https://user-images.githubusercontent.com/205792/77062286-d3f1b500-6998-11ea-8df7-feb1a0d4103d.png)
Call me crazy, but shouldn't you download before connecting :) ?

**Comment by herculeeza** [comment]
I think I switched them by accident... back in order now!

**Comment by adamstallard** [comment]
> I think I switched them by accident... back in order now!

Does this fix still need to be published?

**Comment by adamstallard** [comment]
> I think I switched them by accident... back in order now!

Since brightid.webflow.io still had the issue, I logged in and it still looks inverted on all screens tablet and smaller

**Comment by adamstallard** [comment]
@UBIpromoter Just noticed a typo in the FAQ section of the draft website. At the end of the 'Why doesn’t BrightID use biometrics?' section there are two seemingly vestigial sentences.

Does BrightID use facial recognition?Is there a “Log in with BrightID?”

**Comment by adamstallard** [comment]
> @UBIpromoter Just noticed a typo in the FAQ section of the draft website. At the end of the 'Why doesn’t BrightID use biometrics?' section there are two seemingly vestigial sentences.
> 
> Does BrightID use facial recognition?Is there a “Log in with BrightID?”

I just fixed this

**Comment by herculeeza** [comment]
Ready for review <3

**Comment by adamstallard** [comment]
> Ready for review <3

It gets better every time!

**Comment by adamstallard** [comment]
When it comes to image sizes, the News images automatically had a "srcset" of smaller images created by webflow.  It may be because the width and height are "auto."  That might be an easier way to reduce the file sizes of the partner and team images.  @herculeeza
